# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # OS
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  # SYSTEM
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
    vb.name = "lab_inventory"
  end

  # NETWORKING
  config.vm.network :private_network, ip: "192.168.33.60"
  config.vm.network :forwarded_port, guest: 80, host: 8050
  config.vm.network :forwarded_port, guest: 7000, host: 8750
  config.vm.network :forwarded_port, guest: 8000, host: 8850

  # NFS
  config.vm.synced_folder "../", "/projects/CloudColony", nfs: true

  # PROVISIONER
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.sudo = true
  end
end
