---
- name: Configure the Nginx PPA
  apt_repository: repo=ppa:nginx/{{ nginx_version }} state=present

- name: Install Nginx
  apt: pkg=nginx state=present

- name: Delete default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  register: delete_default_site
  when: nginx_delete_default_site | bool
  notify:
    - Restart Nginx

- name: Delete default web root
  file: path=/var/www/html state=absent
  when: nginx_delete_default_site | bool and delete_default_site | changed

- name: Install gunicorn upstream config
  template: src=gunicorn-upstream.conf.j2 dest=/etc/nginx/sites-enabled/gunicorn-upstream.conf

- name: Install main nginx conf
  template: src=main.conf.j2 dest=/etc/nginx/sites-enabled/main.conf

- name: Delete default nginx sites-enabled config
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Restart nginx
  service: name=nginx state=restarted

